base_url = "https://r-genomics.com"
title = "Regen"

compile_sass = true

highlight_code = true

build_search_index = false

check_external_links = true

taxonomies = [
    {name = "tags", rss = true}
]

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "posts", link = "publication" },
    { text = "about", link = "scientist" },
]

sam_bottom_menu = true

[extra.sam_footer]
text = "Some footer text."
