# Название сайта
title = "Научный Центр"

# Описание сайта
description = "Официальный сайт нашего научного центра, посвященного исследованиям в области физики, информатики и биологии."

# Базовый URL сайта
base_url = "https://r-genomics.com"

# Язык сайта
default_language = "ru"


# Параметры, касающиеся содержания
[extra]
  # Логотип сайта
  logo = "/images/logo.png"
  # Информация для контактов
  contact_email = "info@example.com"
  contact_phone = "+7 (123) 456-7890"


# Параметры меню
[[menu.main]]
  identifier = "about"
  name = "О нас"
  url = "/about/"

[[menu.main]]
  identifier = "research"
  name = "Публикации"
  url = "/publication/"


[[menu.main]]
  identifier = "events"
  name = "События"
  url = "/conf/"


[[menu.main]]
  identifier = "team"
  name = "Команда"
  url = "/team/"
